### ISSUE TITLE
Use as a context manager doesn't work in Python 2.7

### ISSUE THREAD

**Issue by garybernhardt** [garybernhardt/dingus#10]
Herman Sheremetyev found that the examples on the Python mock comparison page don't work with Dingus 0.3.2 and Python 2.7. This bug seems to be shared with Fudge; let them know if we fix it first.

**Comment by garybernhardt** [comment]
I commented out the examples in the mock library comparison where this breaks (https://github.com/garybernhardt/python-mock-comparison/commit/08daf71775eab15b261d1bc19cbc96686946f294). Update it when this is fixed.

**Comment by dowski** [comment]
I just ran up against this. I hacked around it locally - perhaps I'll work on a real fix to share.

**Comment by garybernhardt** [comment]
That would be awfully nice of you...! :)

**Comment by CharString** [comment]
Reason it breaks is this:

> A new opcode was added to perform the initial setup for with statements, looking up the `__enter__()` and `__exit__()` methods. (Contributed by Benjamin Peterson.) http://docs.python.org/dev/whatsnew/2.7.html#optimizations

This passage in the [language reference](http://docs.python.org/reference/datamodel.html#special-method-lookup-for-new-style-classes):

> For new-style classes, implicit invocations of special methods are only guaranteed to work correctly if defined on an object’s type, not in the object’s instance dictionary. 
> tells us that what happened with `__enter__` might happen with all special methods.

mock has MagicMock which binds special methods to the class.

**Comment by garybernhardt** [comment]
Argh... that seems insane. :( I guess that dinguses do already define several magic methods to avoid weirdness (**str**, **len**, **iter**, **deepcopy**), but I hate to add even more.

**Comment by CharString** [comment]
Hmm. Well [here's](https://github.com/CharString/dingus/commit/a9ee067a369bc4b180ef32646393716512235626) a naive fix that passes the library comparison tests again.

But it consumes exceptions raised in the context. And it doesn't have the _parent set, so the calls on the parent aren't complete. I frequently felt things "snap" in my head trying to fix this. :-)

**Comment by garybernhardt** [comment]
Yeah... this was more fun when Python behaved sanely. :/

**Comment by dowski** [comment]
Here's an altered version that passes CharString's tests (even the ones that were commented out).

https://github.com/dowski/dingus/commit/c6a9efae9660bdb920b6d4f33225670dbbc8c5ca

**Comment by garybernhardt** [comment]
I'm confused about the "consumes" stuff. Is that needed, or could this be fixed without it?

**Comment by CharString** [comment]
If you're mocking a context manager that handles certain Exceptions, but not other. You think you'd want to mock that behaviour of the mocked manager.  But, by all means, change the terminology for something better; English is not my mother tongue.

Or throw the idea out, altogether ;-)

**Comment by garybernhardt** [comment]
I merged this with a few tweaks, most notably renaming _consumes => consumed_context_manager_exceptions. I hate that long name, but I can't think of anything shorter that's unambiguous when you see it. (Suggestions welcome.) Thanks for figuring this out, guys.

**Comment by dowski** [comment]
Thank you, Gary.
