### ISSUE TITLE
`patch` will not "patch" nonexistent objects.

### ISSUE THREAD

**Issue by gaconnet** [garybernhardt/dingus#11]
`patch` raises `AttributeError` if you try to patch a name that does not exist.

```
class WhenPatchingMissingObjects:
    @patch('urllib2.missing_object')
    def should_create_object_with_dingus(self):
        assert isinstance(urllib2.missing_object, Dingus)

    def should_delete_object_after_patched_function_exits(self):
        @patch('urllib2.missing_object')
        def patch_urllib2():
            pass
        assert not hasattr(urllib2, 'missing_object')
        patch_urllib2()
        assert not hasattr(urllib2, 'missing_object')
```

Although failing in this case makes sense if you interpret the word "patch" strictly, I found myself wishing I could do this when patching a library dependency that exposed new names as a way to support multiple deployed versions. E.g. `pilate.thrwow_him_to_the_floor` and `pilate.thwow_him_to_the_floor2`, where the newer `2` function is not yet ready for pushing & "pip"ing so I need to stub it in all of the separate projects that want to upgrade their usage.

**Comment by garybernhardt** [comment]
I'm hesitant about this. Wouldn't it be better to do something like this in your test?

```
if not hasattr(pilate, "throw_him_to_the_floor"):
    raise SkipTest
```

so that the test is clearly not actually running when the dependency isn't there?

**Comment by gaconnet** [comment]
That probably would be better. I mostly dislike my proposal as well, because I don't think it's meaningful to claim to be patching something that does not exist, but I wanted to put the idea out there anyway.

I think in my case I would not want to skip the test; I need to keep burning through tickets, implementing--and testing--my end of the code while a teammate writes `thwow_him_to_the_floor2` in whatever library I'll later be pip installing. I could, however, simply import the modules and stub the objects without using the word "patch," which is probably less confusing in the long run.

Thanks for your feedback! You're welcome to close the issue & the pull request if this proposal is not good for Dingus.

**Comment by garybernhardt** [comment]
Closing. I don't think it's in Dingus' scope. :)
