### ISSUE TITLE
Clarify licensing

### ISSUE THREAD

**Issue by saschpe** [garybernhardt/dingus#16]
Hi there, 

could you please clarify the license for dingus? Setup.py states MIT whereas dingus.py says BSD (but which BSD version). We would like to package it for openSUSE but we need a valid licensing statement. Thanks!

**Comment by garybernhardt** [comment]
Done. That comment in dingus.py was left over from before it was even an egg.

**Comment by garybernhardt** [comment]
I also released version 0.3.4 to the package index with this change.

**Comment by saschpe** [comment]
Thank you for the fast reply.
