### ISSUE TITLE
Upload a new version to the cheeseshop!

### ISSUE THREAD

**Issue by ionrock** [garybernhardt/dingus#6]
Hey Gary, 

I realized I started using the patch function from the repo, but we haven't seen a new release for quite some time. Mind pushing a 0.3 to pypi?

Thanks!

**Comment by garybernhardt** [comment]
Done.

**Comment by ionrock** [comment]
The setup is referencing the README.markdown but I don't think it makes it into tar.gz.
Thanks for the release!

**Comment by garybernhardt** [comment]
Sorry about that. Fixed and released as 0.3.1.
