### ISSUE TITLE
DingusTestCase accepts str for exclude parameter

### ISSUE THREAD

**Issue by jaraco** [garybernhardt/dingus#7]
dingus.DingusTestCase accepts a string for the exclude parameter, but such usage is probably not going to do what the user expects. I encountered code that called DingusTestCase(auth.identify, 'NoActiveVersionError'). What the user clearly intended was to exclude the auth.NoActiveVersionError from being made a Dingus. Instead, what NoActiveVersionError is still a dingus and any attributes in the set(['N', 'o', 'A', 'c',..., 'r']) were excluded.

I suggest adding:

```
if isinstance(exclude, basestring):
 raise ValueError("String not allowed for exclude - to exclude a string of characters, use tuple(characters)")
```

or

```
if isinstance(exclude, basestring):
  exclude = [exclude]
```

Either option would probably follow the principle of 'least surprise'.

**Comment by garybernhardt** [comment]
Fixed in garybernhardt/dingus@643ea60f141a9da45acc. Thanks!
